title: Shimon Komarovsky
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/shimon-K/" }
    - { platform: twitter, user_url: "https://twitter.com/ShimonKom" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/shimon-komarovsky-71669925/" }    
google_analytics: G-NGQWNXRS74
highlighter: rouge
kramdown:
    math_engine: katex
    syntax_highlighter: rouge
header-includes:
  - \usepackage{subcaption}
output:
    pdf_document
