title: Shimon Komarovsky
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    twitter: alfcnz
    github:  shimon-K
    youtube_channel: UCupQLyNchb9-2Z5lmUOIijw
    youtube_channel_name: Shimon Komarovsky
google_analytics: G-NGQWNXRS74
highlighter: rouge
kramdown:
    math_engine: katex
    syntax_highlighter: rouge
