title: Shimon Komarovsky
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/shimon-K/" }
    - { platform: twitter, user_url: "https://twitter.com/ShimonKom" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/shimon-komarovsky-71669925/" }    
    - { platform: youtube, user_url: "https://www.youtube.com/c/ArtificialGeneralIntelligence" }  
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=whKPveEAAAAJ%26hl" }
    - { platform: flickr,         user_url: "https://www.flickr.com/photos/whKPveEAAAAJ&hl" }
    - { platform: microdotblog,   user_url: "https://micro.blog/Shimon-Komarovsky" }
  social_links2:
    twitter: ShimonKom
    linkedin: shimon-komarovsky-71669925
    flickr: whKPveEAAAAJ&hl
    github:  shimon-K
    orcid:  0000-0002-9036-0282
    youtube_channel: ArtificialGeneralIntelligence
    youtube_channel_name: Shimon Komarovsky
    microdotblog: Shimon-Komarovsky
    medium: theAGI
    facebook: shimon.kom
google_analytics: G-NGQWNXRS74
highlighter: rouge
kramdown:
    math_engine: katex
    syntax_highlighter: rouge
header-includes:
  - \usepackage{subcaption}
header_pages:
  - cv.md
  - publications.md
  - Teaching.md
  - contact.md
output:
    pdf_document
