title: Shimon Komarovsky
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    twitter: ShimonKom
    linkedin: shimon-komarovsky-71669925
    flickr: whKPveEAAAAJ&hl
    github:  shimon-K
    youtube_channel: UCfyvHxqRzuf4y-VmD3lbLRA
    youtube_channel_name: Shimon Komarovsky
google_analytics: G-NGQWNXRS74
highlighter: rouge
kramdown:
    math_engine: katex
    syntax_highlighter: rouge
header-includes:
  - \usepackage{subcaption}
output:
    pdf_document
footer_icons:
  - username: aterenin/minima-reboot/
    url: https://github.com/aterenin/minima-reboot/
    icon: icon-github.svg
    icon_height: 16px
    icon_width: 16px
