title: Shimon Komarovsky
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    twitter: ShimonKom
    linkedin: shimon-kom-71669925
    github:  shimon-K
    youtube_channel: ArtificialGeneralIntelligence
    youtube_channel_name: Shimon Komarovsky
google_analytics: G-NGQWNXRS74
highlighter: rouge
kramdown:
    math_engine: katex
    syntax_highlighter: rouge
header-includes:
  - \usepackage{subcaption}
output:
    pdf_document
